monolog:
  channels: ['nuonic_searchhub']
  handlers:
    nuonicSearchHubHandler:
      type: rotating_file
      path: "%kernel.logs_dir%/nuonic_searchhub_%kernel.environment%.log"
      level: error
      channels: [ "nuonic_searchhub" ]

