name: Build extension

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: FriendsOfShopware/actions/.github/workflows/store-shopware-cli.yml@main
    with:
      extensionName: NuonicSearchHub
    secrets:
      accountUser: ${{ secrets.SHOPWARE_ACCOUNT_MACHINE_USER }}
      accountPassword: ${{ secrets.SHOPWARE_ACCOUNT_MACHINE_PASSWORD }}
      ghToken: ${{ secrets.GITHUB_TOKEN }}
